#!/usr/bin/env bash
set -e # exit on error
set -x # echo on

# Using "source" instead of e.g. relying on "pre_start" makes env. vars def. in source'd script pass through; e.g. for Gradle wrapper
source ` dirname "$0" `/common

# Application must bind to $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT, and log into OPENSHIFT_DIY_LOG_DIR instead of STDOUT
cd $OPENSHIFT_REPO_DIR/ch.vorburger.xtend.web
echo "start GRADLE_USER_HOME = $GRADLE_USER_HOME"
nohup ../gradlew run -Pappargs="$OPENSHIFT_DIY_IP $OPENSHIFT_DIY_PORT" > ${OPENSHIFT_DIY_LOG_DIR}/gradle-run.log 2>&1 &
